centralstation/apps/accounts/urls.py
__author__ = 'Derek Stegelman'
__date__ = '9/5/12'


from django.conf.urls import patterns, url
from accounts.views import registration, account_home, profile, team_home

urlpatterns = patterns('',
    url(r'^$', account_home, name='account_home'),

    url(r'^(?P<team>[-\w]+)/$', team_home, name='team_home'),
    url(r'^registration/$', registration, name="account_registration"),



)

centralstation/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'centralstation.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

__author__ = 'Derek Stegelman'
__date__ = '9/5/12'

admin.autodiscover()

from sprints.ajax import update_status, change_task

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/login.html'}, name="logout"),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'core.views.homepage', name='homepage'),
    url(r'^myprofile/$', 'accounts.views.profile', name='user_profile'),
    url(r'^registration/$', 'accounts.views.registration', name="account_registration"),


    url(r'^ajax/sprints/', include('sprints.ajax_urls')),



    url(r'^projects/', include('projects.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^(?P<account>[-\w]+)/', include('accounts.urls')),
    url(r'^(?P<account>[-\w]+)/sprints/', include('sprints.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/login.html'}, name="logout"),


    #AJAX
    url(r'^ajax/update/task/(?P<task_id>\d+)/$', change_task, name='ajax_change_task'),
    url(r'^ajax/update/story/(?P<story_id>\d+)/$', update_status, name='ajax_update_status'),


)

if settings.DEBUG:

    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

    urlpatterns += staticfiles_urlpatterns()

centralstation/apps/sprints/models.py
from django.db import models
from django.contrib.auth.models import User

from actstream import action

from sprints.choices import STORY_STATUS_CHOICES, STORY_POINT_CHOICES, STATUS_COLORS, color_choices
from sprints.managers import SprintManager, SprintStoryManager
from accounts.models import Team, Account
from projects.models import Project

__author__ = 'Derek Stegelman, Garrett Pennington'
__date__ = '9/5/12'

class AuditBase(models.Model):
    deleted = models.BooleanField()
    deleted_date = models.DateTimeField(null=True, blank=True)
    created_date = models.DateTimeField(null=True, blank=True, auto_now_add=True)

    class Meta:
        abstract = True

class Sprint(AuditBase):
    name = models.CharField(max_length=250, blank=True, null=True)
    start_date = models.DateField(blank=False, null=True)
    end_date = models.DateField(blank=False, null=True)
    team = models.ForeignKey(Team) # TODO this should be M2M

    locked = models.BooleanField()

    objects = SprintManager()

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return "Sprint from %s through %s" % (str(self.start_date), str(self.end_date))

    def create(self, request):
        action.send(request.user, verb='created', action_object=self, target=self.team)

    def update(self, request):
        action.send(request.user, verb='updated', action_object=self, target=self.team)

    @property
    def total_points(self):
        points = 0
        for sprint_story in SprintStory.objects.filter(sprint=self):
            points = points + sprint_story.points
        return points

    @property
    def completed_points(self):
        points = 0
        for sprint_story in SprintStory.objects.filter(sprint=self):
            # Remember to check for "Terminal" status
            if sprint_story.status.terminal:
                points = points + sprint_story.points
        return points

    def completed_by_status(self):
        total = self.total_points
        perc = []
        for status in self.team.organization.statuses():
            stories_of_a_certain_status = []
            #statuses.append(status.status)
            for sprint_story in SprintStory.objects.filter(sprint=self):
                if sprint_story.status.slug == status.slug:
                    stories_of_a_certain_status.append(sprint_story)
            
            s = {
                'status' : status.status,
                'style_class': status.style_class
            }
            status_points = 0
            for sprint_story in stories_of_a_certain_status:
                status_points += sprint_story.points
            if total > 0:
                s['percentage'] = float(status_points) / float(total) * 100
            else:
                s['percentage'] = 0
            perc.append(s)

        return perc

    def complete(self, moved=True, sprint=None):
        """ Ask user if they want incomplete stories move to the next
         sprint, or moved to the backlog.  If moved to the next sprint,
         force user to create a new sprint object, and then create
         SprintStory objects for that next sprint.  Go ahead
         and use the attributes of the story for now when creating
         the new records.  Points/Status, etc.
        """

        # Get all SprintStory objects for this sprint.
        for sprint_story in SprintStory.objects.by_sprint(self):
            # Check to see if this story
            # is in Terminal state.
            if not sprint_story.status.terminal:
                # It must be.  Add to new sprint object
                # or, move to backlog.
                if moved:
                    if sprint:
                        # Checking to make sure you provided
                        # a sprint.
                        SprintStory.objects.create(sprint=sprint, story=sprint_story.story, status=sprint_story.status, points=sprint_story.points)
                    else:
                        raise ValueError("You must provide a valid sprint to move this object to.")
                else:
                    # Backlog this bitch.
                    # Just realized I have no idea how to do that.  Ugh..
                    sprint_story.story.move_to_backlog(points=sprint_story.points)
            # pass
        
    @models.permalink
    def get_absolute_url(self):
        return ('sprint_detail', (), { 'account': self.team.organization.slug, 'id': self.id })

    @models.permalink
    def get_story_add(self):
        return ('story_add', (), {'account': self.team.organization.slug})

    @models.permalink
    def get_task_add(self):
        return ('task_add', (), {'account': self.team.organization.slug})

    @models.permalink
    def get_sprint_edit(self):
        return ('sprint_edit', (), { 'account': self.team.organization.slug, 'id': self.id })

class Status(models.Model):
    account = models.ForeignKey(Account, null=True)
    status = models.CharField(max_length=250, blank=True, null=True)
    order = models.IntegerField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    color = models.CharField(max_length=20, choices=color_choices())
    initial = models.BooleanField()
    terminal = models.BooleanField()
    
    def __unicode__(self):
        return self.status

    @property
    def style_class(self):
        return STATUS_COLORS[self.color]['style_class']

    @property
    def hex_code(self):
        return STATUS_COLORS[self.color]['hex']
        
    def save(self, *args, **kwargs):
        if self.initial == True:
            statuses = self.account.statuses()
            for status in statuses:
                status.initial = False
                status.save()

        if self.terminal == True:
            statuses = self.account.statuses()
            for status in statuses:
                status.terminal = False
                status.save()
            
        super(Status, self).save(*args, **kwargs)


    class Meta:
        ordering = ['order']


class Story(AuditBase):
    # Valid properties at the top.
    title = models.CharField(max_length=250, blank=False, null=True, help_text="As a User I would like to...")
    project = models.ForeignKey(Project, null=True)
    position = models.IntegerField(blank=True, null=True)
    points = models.IntegerField(choices=STORY_POINT_CHOICES, blank=False, null=False, verbose_name="Difficulty")
    backlog = models.BooleanField()

    # No Longer used.
    status = models.CharField(choices=STORY_STATUS_CHOICES, max_length=20, blank=True, null=True, editable=False)
    status = models.ForeignKey(Status, null=True, blank=True)

    sprint = models.ForeignKey(Sprint, null=True, blank=True)

    def __unicode__(self):
        return self.title

    def create(self, request):
        action.send(request.user, verb='created', action_object=self, target=self.project)

    def close(self, request):
        self.status = 'done'
        action.send(request.user, verb='closed', action_object=self, target=self.project)
        self.save()

    def update(self, request):
        action.send(request.user, verb='updated', action_object=self, target=self.project)

    def mark_roadblocked(self, request):
        self.status = 'road-blocked'
        action.send(request.user, verb='marked as Road Blocked', action_object=self, target=self.project)

    def add_to_sprint(self, sprint):
        """ Add a story to a sprint, creates the story/sprint object
        """

        SprintStory.objects.create(sprint=sprint, story=self, status=self.status, points=self.points)

    def remove_from_sprint(self, sprint):
        """ Remove a story from a sprint.  Deletes the object because
         we do not want a historical record of this being attached to this sprint.
        """

        sprint_story_object = SprintStory.objects.get(sprint=sprint, story=self)
        sprint_story_object.delete()

    def move_to_backlog(self, points):
        """ Mark story as backloged.  Update
         point value if necessary.
        """
        self.backlog = True
        self.points = points
        self.save()


    @models.permalink
    def get_absolute_url(self):
        return ('story_edit', (), {'account': self.project.account.slug, 'pk': self.id})

    @property
    def roadblocked(self):
        for task in self.task_set.all():
            if task.status == 'road-blocked':
                return True
        return False

    class Meta:
        ordering = ['status']


class Task(AuditBase):
    title = models.CharField(max_length=250, blank=False, null=True)
    # Status not used anymore.
    status = models.CharField(choices=STORY_STATUS_CHOICES, max_length=20, blank=True, null=True)
    ticket = models.URLField(blank=True, null=True)
    assigned = models.ForeignKey(User, null=True)

    story = models.ForeignKey(Story, null=True)
    complete = models.BooleanField()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('task_edit', (), {'account': self.get_account().slug, 'pk': self.id})

    def create(self, request):
        action.send(request.user, verb='created', action_object=self, target=self.story)

    def update(self, request):
        action.send(request.user, verb='updated', action_object=self, target=self.story)

    def get_account(self):
        story = SprintStory.objects.filter(story=self.story)[0]
        for story in story:
            return story.sprint.account

class Roadblock(AuditBase):
    title = models.CharField(max_length=250, blank=False, null=True)
    story = models.ForeignKey(Story, null=True, blank=False)

    def __unicode__(self):
        return self.title
        
        
class OrderedStory(AuditBase):
    story = models.ForeignKey(Story, null=True, blank=False)
    position = models.IntegerField(blank=False)

centralstation/apps/accounts/forms.py
__author__ = 'Derek Stegelman'
__date__ = '9/5/12'


from django import forms
from django.forms.widgets import PasswordInput
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Field

class RegistrationForm(forms.Form):

    def __init__(self, *args, **kwargs):

        self.helper = FormHelper()
        self.helper.form_tag = False
        self.helper.help_text_inline = True
        self.helper.form_show_errors = False
        self.helper.layout = Layout(
            Field('username'),
            Field('company_name'),
            Field('email'),
            Field('password'),
            Field('password_confirm'),
        )
        super(RegistrationForm, self).__init__(*args, **kwargs)

    # @TODO - Need to make sure password is entered correctly twice.

    username = forms.CharField()
    company_name = forms.CharField()
    email = forms.EmailField()
    password = forms.CharField()
    password_confirm = forms.CharField()

class UserProfileForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_tag = False
        
        super(UserProfileForm, self).__init__(*args, **kwargs)

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.EmailField()
    change_password = forms.CharField(required=False, widget=PasswordInput)
    change_password_confirm = forms.CharField(required=False, widget=PasswordInput)

    def clean(self):
        cleaned_data = super(UserProfileForm, self).clean()
        if cleaned_data.get('change_password', None):
            password = cleaned_data.get('change_password')
            confirm = cleaned_data.get('change_password_confirm')
            if password != confirm:
                raise forms.ValidationError('Password and Confirm password must match.')

        return cleaned_data

centralstation/apps/accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib import messages

from accounts.forms import RegistrationForm, UserProfileForm
from accounts.models import Account, RoleAssigned, Team

from sprints.models import Sprint

def registration(request):
    context = {}
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            company = form.cleaned_data['company_name']
            try:
                User.objects.get(username=username)
                # No exception raised? Need to return to the form.
                messages.add_message(request, messages.ERROR, "The username %s is already taken." % username)
                context['form'] = form
                return render(request, 'accounts/registration_form.html', context)
            except User.DoesNotExist:
                # Can Create
                user = User.objects.create_user(username, email=email, password=password)

            company = Account.objects.create(company_name=company)




    context = {'form': form}
    return render(request, "accounts/registration_form.html", context)

def account_home(request, account):
    account = Account.objects.get(slug=account)
    request.session['account_slug'] = account.slug
    sprints = Sprint.objects.current().filter(team__organization=account)
    context = {'sprints': sprints}
    return render(request, 'accounts/account_home.html', context)

def team_home(request, account, team):
    context = {}
    account = get_object_or_404(Account, slug=account)
    team = get_object_or_404(Team, slug=team)
    context['account'] = account
    context['team'] = team
    team_sprints = Sprint.objects.current().by_team(team.slug)
    context['team_sprints'] = team_sprints
    return render(request, 'accounts/team_home.html', context)

def profile(request):
    context = {}
    user = User.objects.get(pk=request.user.id)
    teams = RoleAssigned.objects.filter(user=request.user)

    context['teams'] = teams
    if request.method == "POST":
        form = UserProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            if form.cleaned_data['change_password']:
                user.set_password(form.cleaned_data['change_password'])
            user.save()
            messages.add_message(request, messages.SUCCESS, "Your profile has been updated.")
    else:
        form_initial = {}
        form_initial['first_name'] = request.user.first_name
        form_initial['last_name'] = request.user.last_name
        form_initial['email'] = request.user.email


        form = UserProfileForm(initial=form_initial)
    context['profile_form'] = form

    return render(request, "accounts/profile.html", context)

centralstation/apps/accounts/templates/accounts/account_home.html
{% extends "accounts/base.html" %}
{% block page_title %}Home{% endblock %}
{% block main_content %}
{% for sprint in sprints %}
        <h3>Current Sprint for {{ sprint.team }}</h3>
<table class='table table-bordered table-hover'>
    <tr>
        <th>Status</th>
        <th>Item</th>
        <th>Difficulty</th>
        <th>Ticket</th>
        <th>Project</th>
        <th>Person</th>
    </tr>
    {% for story in sprint.story_set.all %}
    <tr class="story {% if story.status == 'road-blocked' or story.roadblocked %}error{% endif %}">
        <td>{% if story.status %}<span class="label {% if story.status == 'Road Blocked' or story.roadblocked %}label-important{% elif story.status.status == 'In Progress' %}label-info{% elif story.status.status == 'Done' %}label-success{% endif %}">{{ story.status.status }}</span>{% endif %}</td>
        <td><a href="{{ story.get_absolute_url }}">{{ story }}</a></td>
        <td><span class="badge {% if story.points == 13 %}badge-important{% elif story.points == 5 %}badge-warning{% elif story.points == 1 %}badge-success{% endif %}">{{ story.points }}</td>
        <td></td>
        <td>{{ story.project }}</td>
        <td>{{ story.assigned.first_name }} {{ story.assigned.last_name }}</td>
    </tr>
    {% if story.task_set.all %}
    {% for task in story.task_set.all %}
    <tr {% if task.status == 'road-blocked' %}class='error'{% endif %}>
        <td>{% if task.status %}<span class="label {% if task.status == 'road-blocked' %}label-important{% elif task.status == 'in-progress' %}label-info{% elif task.status == 'done' %}label-success{% endif %}">{{ task.get_status_display }}</span>{% endif %}</td>
        <td class='cs-row-task'><a href="{{ task.get_absolute_url }}">{{ task }}</a></td>
        <td></td>
        <td>{% if task.ticket %}<a href="{{ task.ticket }}">Issue</a>{% endif %}</td>
        <td>{{ story.project }}</td>
        <td>{{ task.assigned.first_name }} {{ task.assigned.last_name }}</td>
    </tr>
    {% endfor %}
    {% endif %}
    {% endfor %}
</table>
{% endfor %}
{% endblock %}

centralstation/apps/accounts/templates/accounts/base.html
{% extends "base.html" %}
{% block main_title %} - {{ account }} {% endblock main_title %}
{% block title %}Central Station | {{ account }} | {% block page_title %}{% endblock page_title %}{% endblock title %}
{% block head_css %}
    {{ block.super }}
    <link href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.9.0/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
{% endblock head_css %}
{% block sidebar_super %}{% endblock sidebar_super %}
{% block added_nav %}
<li><a href="{% url account_home account=account_slug %}">Current Sprints</a></li>
<li><a href="{% url archived_sprints account=account_slug %}">Archived Sprints</a></li>
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        Sprints
        <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
        {% for sprint in account_sprints %}
        <li><a href="{{ sprint.get_absolute_url }}">{{ sprint.team }} - {{ sprint.start_date }} - {{ sprint.end_date }}</a></li>
        {% endfor %}
        <li class="divider"></li>
        <li><a href="#addSprint" data-toggle="modal">Start New Sprint</a></li>
    </ul>
</li>
<li><a href="{% url backlog account=account_slug %}">Backlog</a></li>
{% endblock added_nav %}
{% block extra_modals %}
<div class="modal hide fade" id="addSprint">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Sprint</h3>
    </div><!-- /.modal-header -->
    <form method='POST' action="{% url sprint_add account=account_slug %}">
        <div class="modal-body">
            {% csrf_token %}
            {% load crispy_forms_tags %}
            {% crispy sprint_form %}
        </div><!-- /.modal-body -->
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <input type="submit" value="Add Project" class="btn btn-primary">
        </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->
{% endblock extra_modals %}
{% block body_js %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}accounts/js/global.js"></script>
{% endblock body_js %}

centralstation/apps/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% block main_content %}
{% block sidebar_super %}{% endblock sidebar_super %}
<form method="POST" action="{% url django.contrib.auth.views.login %}?next=/">{% csrf_token %}
    {% if form.errors %}
    <div class='alert alert-danger'>
        <ul class='unstyled'>
        {% for field in form %}
            {% if form.errors %}
        <li>{{ field.label }} - {{ field.errors|striptags }}</li>
            {% endif %}
        {% endfor %}
        </ul>
    </div><!-- /.alert -->
    {% endif %}
    <div class="control-group">
        <label class="control-label" for="inputUsername">Username</label>
        <div class="controls">
            <input type="text" id="inputUsername" placeholder="Username" name="username">
        </div><!-- /.controls -->
    </div><!-- /.control-group -->
    <div class="control-group">
        <label class="control-label" for="inputPassword">Password</label>
        <div class="controls">
            <input type="password" id="inputPassword" placeholder="Password" name="password">
        </div><!-- /.controls -->
    </div><!-- /.control-group -->
    <input type="submit" value="Log In" class="btn btn-primary">
</form>
{% endblock main_content %}

centralstation/apps/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block main_class %}span9{% endblock main_class %}
{% block sidebar %}
    <h4>Profile Image</h4>
    <img src="{% get_gravatar request.user.email 160 %}" width="160" class="img-rounded">
    <p>Change your avatar at <a href="https://en.gravatar.com/">Gravatar</a>.</p>
    <h4>Your Organizations</h4>
    <ul class='unstyled'>
        {% for team in teams %}
        <li><a href="{{ team.team.organization.get_absolute_url }}">{{ team.team.organization }} - {{ team.team }}</a></li>
        {% endfor %}
    </ul>
{% endblock sidebar %}
{% block main_content %}
    <h3>Your Profile</h3>
    {% load crispy_forms_tags %}
    <form action="." method="POST">
        {% csrf_token %}
        {% crispy profile_form %}
        <input type='submit' value='Update Profile' class="btn btn-primary">
    </form>
{% endblock main_content %}

centralstation/apps/accounts/templates/accounts/registration_form.html
{% extends "base.html" %}
{% block main_content %}
    {% block sidebar_super %}{% endblock sidebar_super %}
    <h3>Register for Central Station</h3>
    {% load crispy_forms_tags %}
    <form method="POST">
        {% crispy form %}
        <div class='form-actions'>
            <input type="submit" value="Sign Me Up!" class="btn btn-primary">
        </div><!-- /.form-actions -->
    </form>
{% endblock main_content %}

centralstation/apps/accounts/templates/accounts/team_home.html
{% extends "accounts/base.html" %}
{% block page_title %}{{ team.name }}|Home{% endblock %}
{% block main_content %}
    <h1>Team: {{ team }}</h1>
    <h3>Stories</h3>
    {% if team_sprints %}
    <ul>
        {% for sprint in team_sprints.all %}
            {% for story in sprint.all %}
            <li>{{ story }}</li>
            {% endfor %}
        {% endfor %}
    </ul>
    {% endif %}
    <h3>Sprints</h3>
    {% if team_sprints %}
    <ul>
        {% for sprint in team_sprints %}
        <li>{{ sprint }}</li>
        {% endfor %}
    </ul>
    {% endif %}
{% endblock %}