centralstation/apps/sprints/urls.py
__author__ = 'Derek Stegelman'
__date__ = '9/5/12'

from django.conf.urls import patterns, url, include

from tastypie.api import Api

from sprints.api import SprintResource
#from sprints.ajax import change_task, update_status
from sprints.views import SprintListView, update_status, update_stories, \
    StoryEditForm, AddStory, AddTask, TaskEditForm, Backlog, AddSprint, SprintEditForm, SprintStoryDetailView, move_to_backlog, MoveToNewSprint, handle_new_story_backlog, ArchivedSprintView

v1_api = Api(api_name="v1")
v1_api.register(SprintResource())

urlpatterns = patterns('',

    #url(r'^(?P<goal_slug>[-\w]+)'),

    url(r'^$', SprintListView.as_view(), name='sprint_list'),
    url(r'^archived/$', ArchivedSprintView.as_view(), name='archived_sprints'),
    url(r'^backlog/$', Backlog.as_view(), name='backlog'),
    url(r'^backlog/new/$', handle_new_story_backlog, name='backlog_add_story'),

    url(r'^sprint/add/$', AddSprint.as_view(), name='sprint_add'),
    url(r'^sprint/edit/(?P<id>\d+)/$', SprintEditForm.as_view(), name='sprint_edit'),

    url(r'^sprint/(?P<id>\d+)/$', SprintStoryDetailView.as_view(), name='sprint_detail'),
    url(r'^sprint/(?P<id>\d+)/move_to_backlog/$', move_to_backlog, name='sprint_move_to_backlog'),
    url(r'^sprint/(?P<id>\d+)/move_to_new_sprint/$', MoveToNewSprint.as_view(), name='sprint_move_to_new_sprint'),


    url(r'^stories/add/$', AddStory.as_view(), name='story_add'),
    url(r'^stories/(?P<pk>\d+)/$', StoryEditForm.as_view(), name='story_edit'),

    url(r'^task/add/$', AddTask.as_view(), name='task_add'),
    url(r'^task/(?P<pk>\d+)/$', TaskEditForm.as_view(), name='task_edit'),
    
    url(r'^update/story-status/$', update_status, name='update_status'),
    url(r'^update/stories/$', update_stories, name='update_stories'),
    # API
    url(r'^api/', include(v1_api.urls)),

    #AJAX
    #/ajax/update/task/13/?value=true
    #/ajax/update/story/24/?value=437

)

centralstation/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'centralstation.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

__author__ = 'Derek Stegelman'
__date__ = '9/5/12'

admin.autodiscover()

from sprints.ajax import update_status, change_task

urlpatterns = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/login.html'}, name="logout"),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'core.views.homepage', name='homepage'),
    url(r'^myprofile/$', 'accounts.views.profile', name='user_profile'),
    url(r'^registration/$', 'accounts.views.registration', name="account_registration"),


    url(r'^ajax/sprints/', include('sprints.ajax_urls')),



    url(r'^projects/', include('projects.urls')),
    url(r'^activity/', include('actstream.urls')),
    url(r'^(?P<account>[-\w]+)/', include('accounts.urls')),
    url(r'^(?P<account>[-\w]+)/sprints/', include('sprints.urls')),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/login.html'}, name="logout"),


    #AJAX
    url(r'^ajax/update/task/(?P<task_id>\d+)/$', change_task, name='ajax_change_task'),
    url(r'^ajax/update/story/(?P<story_id>\d+)/$', update_status, name='ajax_update_status'),


)

if settings.DEBUG:

    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

    urlpatterns += staticfiles_urlpatterns()

centralstation/apps/sprints/models.py
from django.db import models
from django.contrib.auth.models import User

from actstream import action

from sprints.choices import STORY_STATUS_CHOICES, STORY_POINT_CHOICES, STATUS_COLORS, color_choices
from sprints.managers import SprintManager, SprintStoryManager
from accounts.models import Team, Account
from projects.models import Project

__author__ = 'Derek Stegelman, Garrett Pennington'
__date__ = '9/5/12'

class AuditBase(models.Model):
    deleted = models.BooleanField()
    deleted_date = models.DateTimeField(null=True, blank=True)
    created_date = models.DateTimeField(null=True, blank=True, auto_now_add=True)

    class Meta:
        abstract = True

class Sprint(AuditBase):
    name = models.CharField(max_length=250, blank=True, null=True)
    start_date = models.DateField(blank=False, null=True)
    end_date = models.DateField(blank=False, null=True)
    team = models.ForeignKey(Team) # TODO this should be M2M

    locked = models.BooleanField()

    objects = SprintManager()

    def __unicode__(self):
        if self.name:
            return self.name
        else:
            return "Sprint from %s through %s" % (str(self.start_date), str(self.end_date))

    def create(self, request):
        action.send(request.user, verb='created', action_object=self, target=self.team)

    def update(self, request):
        action.send(request.user, verb='updated', action_object=self, target=self.team)

    @property
    def total_points(self):
        points = 0
        for sprint_story in SprintStory.objects.filter(sprint=self):
            points = points + sprint_story.points
        return points

    @property
    def completed_points(self):
        points = 0
        for sprint_story in SprintStory.objects.filter(sprint=self):
            # Remember to check for "Terminal" status
            if sprint_story.status.terminal:
                points = points + sprint_story.points
        return points

    def completed_by_status(self):
        total = self.total_points
        perc = []
        for status in self.team.organization.statuses():
            stories_of_a_certain_status = []
            #statuses.append(status.status)
            for sprint_story in SprintStory.objects.filter(sprint=self):
                if sprint_story.status.slug == status.slug:
                    stories_of_a_certain_status.append(sprint_story)
            
            s = {
                'status' : status.status,
                'style_class': status.style_class
            }
            status_points = 0
            for sprint_story in stories_of_a_certain_status:
                status_points += sprint_story.points
            if total > 0:
                s['percentage'] = float(status_points) / float(total) * 100
            else:
                s['percentage'] = 0
            perc.append(s)

        return perc

    def complete(self, moved=True, sprint=None):
        """ Ask user if they want incomplete stories move to the next
         sprint, or moved to the backlog.  If moved to the next sprint,
         force user to create a new sprint object, and then create
         SprintStory objects for that next sprint.  Go ahead
         and use the attributes of the story for now when creating
         the new records.  Points/Status, etc.
        """

        # Get all SprintStory objects for this sprint.
        for sprint_story in SprintStory.objects.by_sprint(self):
            # Check to see if this story
            # is in Terminal state.
            if not sprint_story.status.terminal:
                # It must be.  Add to new sprint object
                # or, move to backlog.
                if moved:
                    if sprint:
                        # Checking to make sure you provided
                        # a sprint.
                        SprintStory.objects.create(sprint=sprint, story=sprint_story.story, status=sprint_story.status, points=sprint_story.points)
                    else:
                        raise ValueError("You must provide a valid sprint to move this object to.")
                else:
                    # Backlog this bitch.
                    # Just realized I have no idea how to do that.  Ugh..
                    sprint_story.story.move_to_backlog(points=sprint_story.points)
            # pass
        
    @models.permalink
    def get_absolute_url(self):
        return ('sprint_detail', (), { 'account': self.team.organization.slug, 'id': self.id })

    @models.permalink
    def get_story_add(self):
        return ('story_add', (), {'account': self.team.organization.slug})

    @models.permalink
    def get_task_add(self):
        return ('task_add', (), {'account': self.team.organization.slug})

    @models.permalink
    def get_sprint_edit(self):
        return ('sprint_edit', (), { 'account': self.team.organization.slug, 'id': self.id })

class Status(models.Model):
    account = models.ForeignKey(Account, null=True)
    status = models.CharField(max_length=250, blank=True, null=True)
    order = models.IntegerField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)
    color = models.CharField(max_length=20, choices=color_choices())
    initial = models.BooleanField()
    terminal = models.BooleanField()
    
    def __unicode__(self):
        return self.status

    @property
    def style_class(self):
        return STATUS_COLORS[self.color]['style_class']

    @property
    def hex_code(self):
        return STATUS_COLORS[self.color]['hex']
        
    def save(self, *args, **kwargs):
        if self.initial == True:
            statuses = self.account.statuses()
            for status in statuses:
                status.initial = False
                status.save()

        if self.terminal == True:
            statuses = self.account.statuses()
            for status in statuses:
                status.terminal = False
                status.save()
            
        super(Status, self).save(*args, **kwargs)


    class Meta:
        ordering = ['order']


class Story(AuditBase):
    # Valid properties at the top.
    title = models.CharField(max_length=250, blank=False, null=True, help_text="As a User I would like to...")
    project = models.ForeignKey(Project, null=True)
    position = models.IntegerField(blank=True, null=True)
    points = models.IntegerField(choices=STORY_POINT_CHOICES, blank=False, null=False, verbose_name="Difficulty")
    backlog = models.BooleanField()

    # No Longer used.
    status = models.CharField(choices=STORY_STATUS_CHOICES, max_length=20, blank=True, null=True, editable=False)
    status = models.ForeignKey(Status, null=True, blank=True)

    sprint = models.ForeignKey(Sprint, null=True, blank=True)

    def __unicode__(self):
        return self.title

    def create(self, request):
        action.send(request.user, verb='created', action_object=self, target=self.project)

    def close(self, request):
        self.status = 'done'
        action.send(request.user, verb='closed', action_object=self, target=self.project)
        self.save()

    def update(self, request):
        action.send(request.user, verb='updated', action_object=self, target=self.project)

    def mark_roadblocked(self, request):
        self.status = 'road-blocked'
        action.send(request.user, verb='marked as Road Blocked', action_object=self, target=self.project)

    def add_to_sprint(self, sprint):
        """ Add a story to a sprint, creates the story/sprint object
        """

        SprintStory.objects.create(sprint=sprint, story=self, status=self.status, points=self.points)

    def remove_from_sprint(self, sprint):
        """ Remove a story from a sprint.  Deletes the object because
         we do not want a historical record of this being attached to this sprint.
        """

        sprint_story_object = SprintStory.objects.get(sprint=sprint, story=self)
        sprint_story_object.delete()

    def move_to_backlog(self, points):
        """ Mark story as backloged.  Update
         point value if necessary.
        """
        self.backlog = True
        self.points = points
        self.save()


    @models.permalink
    def get_absolute_url(self):
        return ('story_edit', (), {'account': self.project.account.slug, 'pk': self.id})

    @property
    def roadblocked(self):
        for task in self.task_set.all():
            if task.status == 'road-blocked':
                return True
        return False

    class Meta:
        ordering = ['status']


class Task(AuditBase):
    title = models.CharField(max_length=250, blank=False, null=True)
    # Status not used anymore.
    status = models.CharField(choices=STORY_STATUS_CHOICES, max_length=20, blank=True, null=True)
    ticket = models.URLField(blank=True, null=True)
    assigned = models.ForeignKey(User, null=True)

    story = models.ForeignKey(Story, null=True)
    complete = models.BooleanField()

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return ('task_edit', (), {'account': self.get_account().slug, 'pk': self.id})

    def create(self, request):
        action.send(request.user, verb='created', action_object=self, target=self.story)

    def update(self, request):
        action.send(request.user, verb='updated', action_object=self, target=self.story)

    def get_account(self):
        story = SprintStory.objects.filter(story=self.story)[0]
        for story in story:
            return story.sprint.account

class Roadblock(AuditBase):
    title = models.CharField(max_length=250, blank=False, null=True)
    story = models.ForeignKey(Story, null=True, blank=False)

    def __unicode__(self):
        return self.title
        
        
class OrderedStory(AuditBase):
    story = models.ForeignKey(Story, null=True, blank=False)
    position = models.IntegerField(blank=False)

centralstation/apps/sprints/templates/sprints/backlog.html
{% extends "accounts/base.html" %}
{% block head_css %}
{{ block.super }}
    <link rel='stylesheet' href="{{ STATIC_URL }}sprints/css/sprints.css">
{% endblock head_css %}
{% block main_content %}
{% block sidebar_super %}{% endblock sidebar_super %}
<h3>Backlog</h3>
<div class='btn-group'>
    <a href="#addStory" data-toggle="modal" class="btn">Add Story</a>
    <a href="#addProject" data-toggle="modal" class="btn">Add Project</a>
</div><!-- /.btn-group -->
{% load crispy_forms_tags %}
<div class="modal hide fade" id="addStory">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Story</h3>
    </div><!-- /.modal-header -->
    <form method='POST' action="{% url backlog_add_story account=account_slug %}">
        <div class="modal-body">
            {% csrf_token %}
            {% crispy story_form %}
        </div><!-- /.modal-body -->
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <input type="submit" value="Add Story" class="btn btn-primary">
        </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->
<div class="modal hide fade" id="addProject">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Project</h3>
    </div><!-- /.modal-header -->
    <form method='POST' action="{% url project_add %}">
        <div class="modal-body">
            {% csrf_token %}
            {% crispy project_form %}
        </div><!-- /.modal-body -->
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <input type="submit" value="Add Project" class="btn btn-primary">
        </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->
<table class='table table-bordered table-hover'>
    <tr>
        <th>Status</th>
        <th>Item</th>
        <th>Difficulty</th>
        <th>Ticket</th>
        <th>Project</th>
        <th>Person</th>
        <th>Action</th>
    </tr>
    {% for story in stories %}
    <tr class="story {% if story.status == 'road-blocked' or story.roadblocked %}error{% endif %}">
        <td>{% if story.status %}<span class="label {% if story.status == 'road-blocked' or story.roadblocked %}label-important{% elif story.status == 'in-progress' %}label-info{% elif story.status == 'done' %}label-success{% endif %}">{{ story.get_status_display }}</span>{% endif %}</td>
        <td><a href="{{ story.get_absolute_url }}">{{ story }}</a></td>
        <td><span class="badge {% if story.points == 13 %}badge-important{% elif story.points == 5 %}badge-warning{% elif story.points == 1 %}badge-success{% endif %}">{{ story.points }}</td>
        <td></td>
        <td>{{ story.project }}</td>
        <td>{{ story.assigned.first_name }} {{ story.assigned.last_name }}</td>
        <td>
            <div class="btn-group">
                <button class="btn btn-primary">Action</button>
                <button class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    <li><a href="#">Add to Sprint</a></li>
                    <li><a href="#">Delete</a></li>
                </ul>
            </div><!-- /.btn-group -->
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock main_content %}

centralstation/apps/sprints/templates/sprints/sprint_detail.html
{% extends "accounts/base.html" %}
{% block head_css %}
    {{ block.super }}
    <link rel='stylesheet' href="{{ STATIC_URL }}sprints/css/sprints.css">
{% endblock head_css %}
{% block page_title %}{{ sprint }}{% endblock page_title %}
{% block main_content %}
{% block sidebar_super %}
{% endblock sidebar_super %}
<div class="navbar navbar-fixed-bottom">
    <div class="navbar-inner">
        <span class="brand">Sprint {{ sprint.start_date }} through {{ sprint.end_date }}</span>
        <ul class="nav">
            <li><a href="#addProject" data-toggle="modal">Add Project</a></li>
            <li class="divider-vertical"></li>
            <li><a href="#addStory" data-toggle="modal">Add Story</a></li>
            <li class="divider-vertical"></li>
            <li><a href="#addTask" data-toggle="modal">Add Task</a></li>
            <li class='divider-vertical'></li>
            <li><a href="{{ sprint.get_sprint_edit }}">Edit Sprint</a></li>
            <li class='divider-vertical'></li>
            <li><a href="#completeSprint" data-toggle="modal">Complete Sprint</a></li>
        </ul>
    </div><!-- /.navbar-inner -->
</div><!-- /.navbar -->
<div class="modal hide fade" id="completeSprint">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Complete Sprint</h3>
    </div><!-- /.modal-header -->
    <form method="POST" action="{{ sprint.get_task_add }}">
        <div class="modal-body">
            You have unfinished stories on this sprint.  You can either
            move the stories to a new sprint, or move all unfinished stories
            to the backlog.
        </div><!-- /.modal-body -->
        <div class="modal-footer">

            <a href="{% url sprint_move_to_new_sprint account=sprint.team.organization id=sprint.id %}" class="btn btn-success">Move to Next Sprint</a>
            <a href="{% url sprint_move_to_backlog account=sprint.team.organization id=sprint.id %}" class="btn btn-primary">Move to Backlog</a>
            <a href="#" class="btn" data-dismiss='modal'>Close</a>
        </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->


<div class="modal hide fade" id="addTask">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Task</h3>
    </div><!-- /.modal-header -->
    <form method="POST" action="{{ sprint.get_task_add }}">
    <div class="modal-body">
        {% load crispy_forms_tags %}
            {% csrf_token %}
        {% crispy task_form %}
    </div><!-- /.modal-body -->
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss='modal'>Close</a>
        <input type="submit" value="Add Task" class="btn btn-primary">
    </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->
<div class="modal hide fade" id="addStory">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Story</h3>
    </div><!-- /.modal -->
    <form method='POST' action="{{ sprint.get_story_add }}">
    <div class="modal-body">
        {% csrf_token %}
        {% crispy story_form %}
        <input type="hidden" name="sprint" value="{{ sprint.id }}">
    </div><!-- /.modal-body -->
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
        <input type="submit" value="Add Story" class="btn btn-primary">
    </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->
<div class="modal hide fade" id="addProject">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3>Add Project</h3>
    </div><!-- /.modal-header -->
    <form method='POST' action="{% url project_add %}">
        <div class="modal-body">
            {% csrf_token %}
            {% crispy project_form %}
            <input type="hidden" value="{{ account.id }}" name="account">
            <input type="hidden" value="{{ sprint.id }}" name="sprint">

        </div><!-- /.modal-body -->
        <div class="modal-footer">
            <a href="#" class="btn" data-dismiss="modal">Close</a>
            <input type="submit" value="Add Project" class="btn btn-primary">
        </div><!-- /.modal-footer -->
    </form>
</div><!-- /.modal -->
<div id='cs-sprint-switcher' class="btn-toolbar">
    <div class="btn-group" data-toggle="buttons-radio"> 
        <button id='cs-sprint-table-button' type='button' class="btn active" data-toggle="button"><i class="icon-list"></i></button>
        <button id='cs-sprint-board-button' type='button' class="btn" data-toggle="button"><i class="icon-th-large"></i></button>
    </div><!-- /.btn-group -->
</div><!-- /#cs-sprint-switcher -->
<table id='cs-sprint-board' class="table table-bordered">
{% regroup sprint_stories by status as story_list %}
<thead>
    <tr>
    {% for col in statuses %}
        <th>
            <div class="btn-{{ col.style_class }}">{{ col.status }}</div>
        </th>
    {% endfor %}
    </tr>
</thead>
<tbody>
    <tr>
    {% for column in story_list %}
    <td class='cs-sprint-board-cell'>
        <ul id='cs-sprint-board-{{ column.grouper.slug }}' class='cs-sprint-board-column cs-sprint-board-column-list' data-column='{{ column.grouper.slug }}'>
            {% for sprint_story in column.list %}
            <li id='cs-story-card_{{ sprint_story.id }}' class='cs-story-card' data-story-id='{{ sprint_story.id }}'>
                <div class='cs-story-card-points circle {% if sprint_story.points == 13 %}circle-big{% elif sprint_story.points == 5 %}circle-medium{% elif sprint_story.points == 1 %}circle-small{% endif %}'>{{ sprint_story.points }}</div>
                <p class='cs-story-card-title'><a href="{{ sprint_story.get_absolute_url }}">{{ sprint_story.story.title }}</a></p>
                <p class='cs-story-card-title'>{{ story.task_set.all|length }} Tasks</p>
                <div class='cs-tasks-menu'>
                    <span><a href='#addTask' data-toggle='modal'>Add Task</a></span>
                    <span><a href='#'>Hide Tasks</a></span>
                </div><!-- /.cs-tasks-menu -->
                {% include 'sprints/tasks.html' %}
                <div class='clear'></div>
            </li>
            {% endfor %}
        </ul>
    </td>
    {% endfor %}
    </tr>
</tbody>
</table>

<table id='cs-sprint-table' class='table table-bordered table-hover tablesorter'>
    <thead>
        <tr>
            <th style="width: 50px;">Points</th>
            <th>Item</th>
            <th style="width: 150px;">Status</th>
            <th>Project</th>
            <th>Person</th>
        </tr>
    </thead>
    <tbody>
    {% for sprint_story in sprint_stories %}
        <tr class="story {% if sprint_story.story.status == 'road-blocked' or sprint_story.story.roadblocked %}error{% endif %}" id="story_{{ story.id }}">
            <!-- Let's find a new place for this modal.  not valid markup -->
            <div class="modal hide fade" id="addTaskStory_{{ sprint_story.story.id }}">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3>Add Task</h3>
                </div><!-- /.modal-header -->
                <form method="POST" action="{{ sprint.get_task_add }}">
                    <div class="modal-body">
                        {% load crispy_forms_tags %}
                        {% csrf_token %}
                        {% crispy story_task_form %}
                        <input type="hidden" name="story" value="{{ sprint_story.story.id }}">
                        <input type='hidden' name="sprint" value="{{ sprint.id }}">
                    </div><!-- /.modal-body -->
                    <div class="modal-footer">
                        <a href="#" class="btn" data-dismiss='modal'>Close</a>
                        <input type="submit" value="Add Task" class="btn btn-primary">
                    </div><!-- /.modal-footer -->
                </form>
            </div><!-- /.modal -->
            <td>
                <div class='circle {% if sprint_story.points == 13 %}circle-big{% elif sprint_story.points == 5 %}circle-medium{% elif sprint_story.points == 1 %}circle-small{% endif %}'>{{ sprint_story.points }}</div>
            </td>
            <td>
                <div class='cs-story-item'>
                    <a class='cs-story-item-title' href="{{ sprint_story.story.get_absolute_url }}">{{ sprint_story.story.title }}</a>
                    {% include 'sprints/tasks.html' %}
                    <div class='cs-tasks-menu'>
                        <span><a href='#addTaskStory_{{ sprint_story.story.id }}' data-toggle='modal'>Add Task</a></span>
                        <span><a href='#'>Hide Tasks</a></span>
                    </div><!-- /.cs-tasks-menu -->
                <div><!-- /.cs-story-item -->
            </td>
            <td>            
                <div class="btn-group">
                    <a style="width: 125px;" class="btn dropdown-toggle cs-story-status-item-current btn-{{ sprint_story.status.style_class }}" data-toggle='dropdown' data-story-id='{{ sprint_story.id }}'>
                        <span class="cs-story-status-item-current-name">
                        {% if sprint_story.status %}
                        {{ sprint_story.status.status }}
                        {% else %}
                        ------
                        {% endif %}
                        </span>
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                        {% for status in statuses %}
                        <li>
                            <a class='cs-story-status-item' data-story-status-id='{{ status.id }}' data-story-id='{{ sprint_story.id }}' data-value='{{ status.slug }}'>{{ status.status }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div><!-- /.btn-group -->
            </td>
            <td>{{ sprint_story.story.project }}</td>
            <td>{{ sprint_story.story.assigned.first_name }} {{ sprint_story.story.assigned.last_name }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>

<h3>Stats</h3>
<div class="well well-small">
    <div class="progress">
        {% for status in sprint.completed_by_status %}
        <div class="bar bar-{{ status.style_class }} cs-progress-bar-item" style="width: {{ status.percentage }}%;" data-status='{{ status.slug }}'>{{ status.status }}</div>
        {% endfor %}
    </div>
</div>
<table class="table table-bordered">
    <tr>
        <th>Stat</th>
        <th>Value</th>
    </tr>
    <tr>
        <td>Total Story Points</td>
        <td>{{ total_points }}</td>
    </tr>
    <tr>
        <td>Completed Points</td>
        <td>{{ completed_points }}</td>
    </tr>
</table>
{% endblock main_content %}
{% block body_js %}
    {{ block.super }}
    <script>
        var csrf_token = "{{ csrf_token }}";
    </script>
    <script src="{{ STATIC_URL }}js/jquery.tablesorter.min.js"></script>
    <script src="{{ STATIC_URL }}sprints/js/sprints.js"></script>
{% endblock body_js %}

centralstation/apps/sprints/templates/sprints/sprint_list.html
{% extends 'accounts/base.html' %}
{% block main_content %}
    <ul>
        {% for sprint in sprints %}
    <li><a href="{{ sprint.get_absolute_url }}">{{ sprint.name }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

centralstation/apps/sprints/templates/sprints/story_list.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>

</body>
</html>

centralstation/apps/sprints/templates/sprints/tasks.html
<div class='cs-tasks'>
    <ul>
        {% if sprint_story.story.task_set.all %}
        {% for task in sprint_story.story.task_set.all %}
        <li style="line-height: 30px;" id='cs-task-item-{{ task.id }}' class='cs-task-item{% if task.complete %} cs-task-item-completed{% endif %}' data-task-id='{{ task.id }}'>
            <div>
                <input type='checkbox' id='cs-task-item-complete-{{ task.id }}' class='cs-task-item-complete' data-task-id='{{ task.id }}' {% if task.complete %}checked{% endif %} />
            </div>
            <span class="cs-task-item-title"><a href="{{ task.get_absolute_url }}">{{ task }}</a></span>
            {% if task.ticket %}<span style="margin-left: 10px;"><a href="{{ task.ticket }}">Issue</a></span>{% endif %}
            <!--{% if task.assigned %}<span style="margin-left: 10px;">{{ task.assigned.first_name }} {{ task.assigned.last_name }}</span>{% endif %} -->
        </li>
        {% endfor %}
        {% endif %}
    </ul>
</div><!-- .cs-tasks -->